//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoiceHandling.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuoteRequestDetail
    {
        public int Id { get; set; }
        public int QuoteRequestId { get; set; }
        public int ServiceProviderId { get; set; }
        public Nullable<int> RefId { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> ModifiedAt { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
    
        public virtual QuoteRequest QuoteRequest { get; set; }
        public virtual ServiceProvider ServiceProvider { get; set; }
    }
}
