//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoiceHandling.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quotation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Quotation()
        {
            this.QuotationItems = new HashSet<QuotationItem>();
        }
    
        public int Id { get; set; }
        public Nullable<int> RefferenceId { get; set; }
        public Nullable<int> ApprovedAdminId { get; set; }
        public Nullable<decimal> EstimatedSubTotal { get; set; }
        public Nullable<decimal> EstimatedServiceFee { get; set; }
        public Nullable<decimal> EstimatedTotal { get; set; }
        public string JobDescription { get; set; }
        public int ServiceProviderId { get; set; }
        public Nullable<int> Status { get; set; }
        public int QuatationRequestId { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> ModifiedAt { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
    
        public virtual ServiceProvider ServiceProvider { get; set; }
        public virtual QuoteRequest QuoteRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuotationItem> QuotationItems { get; set; }
    }
}
