//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoiceHandling.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkOrder
    {
        public int Id { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string Description { get; set; }
        public Nullable<int> ServiceProviderID { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> ModifiedAt { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
        public string PropertyHolderName { get; set; }
        public string PHAddress { get; set; }
        public string PHPhoneNumber { get; set; }
        public Nullable<int> TaskId { get; set; }
    
        public virtual ServiceProvider ServiceProvider { get; set; }
        public virtual Task Task { get; set; }
    }
}
